# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20191015_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_Comment', to='wall.Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Comment', to='login.Users'),
        ),
    ]
