# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-09 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='not available'),
            preserve_default=False,
        ),
    ]
