# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-09 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_remove_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_books',
            field=models.ManyToManyField(to='Main.Book'),
        ),
    ]
