# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-09 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_remove_author_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
