# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-09 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20191009_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='Main.Book'),
        ),
    ]
