# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-16 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='sample desc'),
            preserve_default=False,
        ),
    ]
